# Generated by Django 4.2.7 on 2023-11-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='upload',
            new_name='updated',
        ),
    ]
