# Generated by Django 4.2.7 on 2023-11-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop_app', '0002_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
        migrations.DeleteModel(
            name='place',
        ),
    ]
